### ISSUE TITLE
NBrightPayPal 1.0.6 ignores NBright settings (Version 3.5.0)

### ISSUE THREAD

**Issue by mgarub** [nbrightproject/NBrightBuy#103]
when tax is included in price, then the total amount on paypal is item-value + tax + shipping.

total value from shop where both are included should be charged.

With setting no tax -> PP --> Total + Shipping
with settings tax incl in price --> PP --> Total + Shipping + Tax

seems to be a bug for me in NBrightPayPal 1.0.6 - because the calculation for the orders are correct.

How to tell NBrightPayPal 1.0.6 just to charge Total on PayPal?

http://store.zander-guide.de/

Any suggestions

King regards

Martin

**Comment by leedavi** [comment]
Try the latest PP provider and lets see if that's the same.

you can download it from here

http://nbsdocs.nbrightproject.org/Documentation/Downloads

**Comment by mgarub** [comment]
i have a 2nd test installation on http://shop.zander-guide.de/ with 3.5.2 and PP 1.0.8 downloaded today.

Same situation: Total to pay and payment value on paypal does not match. 

On paypal tax and shipping is charged extra. tax is not  charged on paypal if switch for tax in NBright is set to no tax. if tax flag is set to "Tax included in price" paypal will charge it extra.

Any suggestion what might be wrong

**Comment by mgarub** [comment]
one follow up. in paydata.cs you create the data transmitted to paypal like this

`Amount = (appliedtotal - alreadypaid).ToString("0.00", CultureInfo.InvariantCulture);
            Email = oInfo.PurchaseInfo.GetXmlProperty("genxml/billaddress/textbox/billaddress");
            if (!Utils.IsEmail(Email)) Email = oInfo.PurchaseInfo.GetXmlProperty("genxml/extrainfo/textbox/cartemailaddress");
            ShippingAmount = oInfo.PurchaseInfo.GetXmlPropertyDouble("genxml/shippingcost").ToString("0.00", CultureInfo.InvariantCulture);
TaxAmount = oInfo.PurchaseInfo.GetXmlPropertyDouble("genxml/taxcost").ToString("0.00", CultureInfo.InvariantCulture);`

i can't see any check against the store settings. amount calculation could be

Amount = (appliedtotal - alreadypaid - ShippingAmount - TaxAmount)  

or setting ShippingAmount - Taxamount to 0.00 if included in appliedtotal.

kind regards

Martin

**Comment by leedavi** [comment]
Hi Martin,

Yes, most gateways just ask for the amount to be paid.  It has been over 3 years since I wrote that gateway, so I can;t remember the details of paypal, but the code was based on the original v2 version which was written over 8 years ago.  Maybe it's wrong, but it's odd that it's never been pointed this out before.  Before I change the code, can you check the settings of paypal and see if there is an option to not included the tax values in the charged amount?  It's an easy fix in the code but I'm reluctant to change such established code, there could be some option in paypal that makes this work as expected.

**Comment by leedavi** [comment]
Hi Martin,

I've chased this up on paypal and I can't find any option on paypal.  I find it very strange and worrying that this is now wrong.  I know I had to change this payment provider a short while back because the language format of the amount was forced to become en-US, where as before it was always OK.

I also notice that my sandbox account seems to be an older version of the system, so I have no confidence in paypal.

But I've created a new version of the provider (v1.0.9) which removes the tax and shipping amounts.  

Lets hope nobody starts complaining that paypal doesn't add the tax and shipping now!

http://nbsdocs.nbrightproject.org/Documentation/Downloads

**Comment by leedavi** [comment]
I rushed into that change and missed something.  I've upload a new version.

you need v1.1.0

**Comment by mgarub** [comment]
Dear David,
now it is working for me in case 3.5.2 is installed at the same time.

I just want to let you notice, that together with 3.5.0 trying to chanage the settings for the PalPalProvider in NBS Backoffice results in an exception, see below.

The error disappears after installing 3.5.2

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:3fac7b77-a543-4aca-a388-8be8c1000f73

AssemblyVersion:8.0.4
PortalId:0
UserId:1
TabId:79

RawUrl:/Admin/NBS-Backoffice/ctrl/nbrightpaypalpayment
Referrer:http://store.zander-guide.de/Admin/NBS-Backoffice/ctrl/nbrightpaypalpayment
UserAgent:Mozilla/5.0 (Windows NT 6.3; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0

ExceptionHash:H1wOTtuQW6wjjAhdYi75Rw==

Message:Method not found: 'Void NBrightDNN.NBrightInfo.SetXmlProperty(System.String, System.String, System.TypeCode, Boolean, Boolean, Boolean)'.

StackTrace:

InnerMessage:Method not found: 'Void NBrightDNN.NBrightInfo.SetXmlProperty(System.String, System.String, System.TypeCode, Boolean, Boolean, Boolean)'.

InnerStackTrace:

   at Nevoweb.DNN.NBrightBuyPayPal.NBrightPayPalPayment.Update()
   at Nevoweb.DNN.NBrightBuyPayPal.NBrightPayPalPayment.CtrlItemCommand(Object source, RepeaterCommandEventArgs e)
   at System.Web.UI.WebControls.Repeater.OnItemCommand(RepeaterCommandEventArgs e)
   at System.Web.UI.WebControls.Repeater.OnBubbleEvent(Object sender, EventArgs e)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.WebControls.RepeaterItem.OnBubbleEvent(Object source, EventArgs e)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: h2595647

Thanks for helping me out of this problem.

Martin
