### ISSUE TITLE
Several issues with the new store

### ISSUE THREAD

**Issue by MartyNZ** [nbrightproject/NBrightBuy#2]
1. When adding products, after adding a product I have to exit BO and clear the cache, then go back in to BO to add the next product.
2. I've added one product and forgot to add it to the relevant category, I went back in and added it to the category but now the parent category shows in the store front even though it is not listed in that category.
3. I have added ONLY a retail price to each product. The retail price displays in list view but in detail view the price displayed is $0.00.
4. Detail view displays 'itemlistfield Wishlist: itemlistcount' above product image
5. List view displays 'Wishlist: itemlistcount' above each item.
6. I want to be able to display the categories on the store front and drill down to product lists. Used to be able to do this by setting up an 'All Products' parent category in the old store. Is this possible in this new one?

**Comment by leedavi** [comment]
Thx for the feedback Marty.  I know the caching issue on product update, it does try and clear the cache, but it looks like I'll need to clear ALL DNN cache, which I was hoping to avoid.

Not sure on your issues on categories, not sure what your explanation is saying?... can you give me detail s on how to recreate.

I'm guessing the 0.00 is a setting issue.

The wishlist functionality was altered due to a issue with the ipad running safari, which is sh*t.  I think we need to update the defgault templates.

Did you follow this document..

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx

also have a look at this.

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/WishLists.aspx

The documentation is a work in progress, you'll need to bear with us.  

Let me know how you get on, I have a numbe rof store live with this software and it is stable, but the setup is not always easy and sometime simply not saving the settings of modules or back office can cause issues.  The whole thing is turned towards being template driven, which sometime makes this difficult to work "out of the box"

**Comment by MartyNZ** [comment]
Thanks for your response David,
I’ll check those links and let you know how I get on.

As I said, this version is showing great promise. The learning curve is quite steep, but I’m sure it will be worth it.

Cheers
MartyNZ

**Comment by MartyNZ** [comment]
Hi David,
Re: categories. take a quick look at http://www.auroratables.co.nz to get an idea of what I'm after.
I've been poking around and it may be that the 'Drilldown' option in the CategoryMenu module will do what I'm looking for. Problem is I've installed that module and it's not displaying my categories,... at all... :-( using either Drilldown or TreeView. Any ideas on why this would be?

**Comment by MartyNZ** [comment]
NOTE:  Looks like item 3 was an issue with the Cygnus Theme. I've changed the theme to 'Classic' on every module and prices seem to be displaying correctly now.

**Comment by MartyNZ** [comment]
One more question. The site I'm currently building sells vintage audio equipment and as such there is only ever 1 item for sale, so is it possible to disable/hide the 'product quantity' control?

Getting closer to a site that works for me :-)

**Comment by leedavi** [comment]
The categories are hidden when you forst create them, make sure you've unchecked the hidden flag.
And yes use the drilldown option on the menu. like this.. 

http://www.6car.fr/V%C3%A9hicules-neufs/Listing/catref/vehicules-neufs

The Cygnus theme is still not stable for the products, hence the reason the instructions tell you to use Classic.  To hide the quantity just alter the template or css to hide it, don't remove it it's needed for the postback on the buy but hiding it shouldn't cause a problem.

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Templates/ProductListTemplates.aspx

**Comment by MartyNZ** [comment]
Hi David,
I've hidden the quantity control ( the quantityoptions div)
Now the buy button doesn't work!

Also, I was aware of the hidden setting on categories and have unchecked it on all categories. Categories still not showing.

**Comment by MartyNZ** [comment]
Correction to above note. hiding the quantityoptions div did not cause the the buy button to stop working. It now doesn't work no matter what I do??!

i can no longer add items to the cart or checkout

**Comment by leedavi** [comment]
You might need to clear the cache to see the categories.  As for the buy button, check for some kind of JS error or something on the page.

**Comment by MartyNZ** [comment]
Hi David.
1. Still no resolution on the categories not displaying. I've cleared the cache, recycled the application domain. I've even done an iisreset on the server, (and yes, I've made sure the 'hidden' option is unticked) still can't see the categories on the home page.
1. The only JS error I seem to be getting is on page load as shown in image attached. Clicking the buy button does not generate an error (that I can see). I've turned on debug mode and debug file output. Where does it put the file?

cheers
MartyNZ
![onpageload](https://cloud.githubusercontent.com/assets/13032309/8557675/fd4bfc92-2552-11e5-868b-6e5aa32fb7b5.PNG)

**Comment by leedavi** [comment]
That JS error looks like a setting missing!!

I'll need to have a look at your site to understand why categories are not displaying, send me a link and login to dcl @ nevoweb .com and i'll take a look.

**Comment by leedavi** [comment]
OK, the category drilldown is setup to only display when no product are viewed on the product list, this is done by the template if you need to change it. But I've rejigged the category structure and added product list to show you how the base templates expect to be setup for the drill down.

**Comment by MartyNZ** [comment]
I’m sorry but now I’m more confused than ever!!!!!
You say you’ve ‘rejigged’ the category structure, I get that, that is how it had to be done in the old system – with a root or ‘All Products’ base category, but my home page now has an extra category menu module (that makes it two on the home page) a new product view module, and still not a single product, or more importantly category, is being displayed!!!!! Even when I change one of the category menu’s to treeview it doesn’t display the categories!!!

Cheers
Martyn Cook
021 0221 2627

**Comment by MartyNZ** [comment]
BTW:
You still haven't addressed the issue of the 'Buy' button failing to add items to the cart...

**Comment by leedavi** [comment]
Hi Marty,
I know this is an old thread, but just found it in my inbox. 
The problem with the buy button is because the default Cygnus theme has a bug.  You need to select the "Classic" theme in the product view settings, as explained in the install doc.

http://nbsdocs.nbrightproject.org/Documentation/Integratorguide/Installation.aspx

**Comment by MartyNZ** [comment]
Thanks for getting back to me David,
To be honest I put this aside a while ago as I could see you were having a few issues. I’ll be revisiting this shortly.

Cheers
Martyn Cook
021 0221 2627
