### ISSUE TITLE
Collect from store

### ISSUE THREAD

**Issue by Tychodewaard** [nbrightproject/NBrightBuy#63]
In the Checkout settings there is a checkbox 'Collect from store'
What I expected it to do is:
- to have an extra shipping option (either choosing shipping address oor on the review order page)
- shipping costs go to zero

Right now, I have checked the option but nothing seems to have happened.

Tycho

**Comment by leedavi** [comment]
Hi,
That setting is a legacy option. (I'll remove form the next release)

To get a "Collect from store" option you need to add a new plugin and copy the standard shipping plugin and alter the shipping settings of that  to be free deliver.

**Comment by Tychodewaard** [comment]
That was easy...It amazes me every day how easy it is. I can see that NbrightBuy is made with love. Remind me to give you loads of beer in Girona :-)

**Comment by leedavi** [comment]
hehe... that's easy beer is free in Girona, but I'll let you pour one for me.  :-)

Some things are good and I think the flexibility is going in the right direction.  But there's always more things to be done!  Tricky when we have no funding for those part, but hopefully we'll get it done.  that's why it's important to get people like you to help when testing and sponsoring functionality.

If fact I'll pour you a beer in Girona.  :-)

**Comment by Tychodewaard** [comment]
We have a date 😄
If I can sponsor #46 regarding css / ux , i'll be happy to.

**Comment by leedavi** [comment]
Already included that change in the next release :-)

Although I'm not happy with the DNN control bar hiding the message when logged in as admin. But the DNN bar is using JS so we can't seem to put it over it with css.  But I've made it slightly bigger so you can see if it pops up.

**Comment by Tychodewaard** [comment]
Great. When is the next release planned?

**Comment by leedavi** [comment]
Next week hopefully, I'll send you a copy when it's ready for beta.
