### ISSUE TITLE
duplicate article

### ISSUE THREAD

**Issue by Puppyknucks** [nbrightproject/NBrightBuy#82]
I'd like to suggest a duplicate article option as I will be adding a lot of products to my store that are a lot a like and duplicating an article and changing details would make the process a lot easier.

**Comment by leedavi** [comment]
You have a "Save As" option on the article

**Comment by DigitalTrading** [comment]
Just a heads up, we just found an issue with "Save As" option. When you Save as on a product with related items its duplicating the new product by the number of related items. So we saved as once and found it duplicated 14 times. 
This issue seems to come from line 1339 of ProductsData.cs which should be set to objCtrl.Update(dr3);

**Comment by leedavi** [comment]
the push request has been accepted to solve this.
